import React from "react";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "CONTACTOS",
  description: "Generated by Gramaphenia",
};

const page = () => {
  return (
    <div>
      <h1 className="text-[var(--light)]">Contactos</h1>
    </div>
  );
};

export default page;
